-- 0007：notifications.rejected —— 记录「调用被拒绝」的历史
--
-- 背景：key 停用后外部系统往往仍按原节奏调用 /hook/:key。原先直接 403 走人、不留任何记录，
-- 用户只能看到「对方说发了、我这边什么都没有」，无从排查是漏推送还是被拒。
-- 现在被拒绝的调用也写一条通知（只入库不推送），rejected 存拒绝原因，历史里展示为「停用拒绝」。
--
-- ⚠️ 非幂等：SQLite 的 ALTER TABLE ADD COLUMN 没有 IF NOT EXISTS，只能执行一次
-- （重复执行报 duplicate column name: rejected）。
--
-- 执行（⚠️ 必须带 --remote，否则只作用于本地库）：
--   wrangler d1 execute notify-hub --remote --file=./migrations/0007_notifications_rejected.sql
--
-- 取值：NULL = 正常；'key_disabled' = key 已停用被拒。
ALTER TABLE notifications ADD COLUMN rejected TEXT;
